{
  "beige_sophistication_kurti.jpg": { "stock": 15 },
  "bridal_collection_bottle_green_color_pure.jpg": { "stock": 5 },
  "crimson_elegance_kurti.jpg": { "stock": 12 },
  "lavender_kurti.jpg": { "stock": 0 },
  "lavender_saree.jpg": { "stock": 8 },
  "lehenga_crimson_queen_anarkali.jpg": { "stock": 3 },
  "lehenga_golden_marigold_majesty.jpg": { "stock": 7 },
  "lehenga_imperial_scarlet_majesty.jpg": { "stock": 4 },
  "lehenga_royal_mocha_elegance.jpg": { "stock": 0 },
  "lehenga_sapphire_royale.jpg": { "stock": 6 },
  "lehenga_starry_maroon_bridal_glamour.jpg": { "stock": 2 },
  "long_dress_azure_enchantress.jpg": { "stock": 10 },
  "long_dress_blush_petals_reverie.jpg": { "stock": 0 },
  "long_dress_celestial_grace.jpg": { "stock": 8 },
  "long_dress_deep_plum_stardust.jpg": { "stock": 5 },
  "long_dress_emerald_elegance.jpg": { "stock": 9 },
  "long_dress_golden_sunshine_radiance.jpg": { "stock": 11 },
  "long_dress_moonlit_wisteria.jpg": { "stock": 0 },
  "long_dress_rose_stardust.jpg": { "stock": 4 },
  "majestic_green_kurti.jpg": { "stock": 14 },
  "purple_saree.jpg": { "stock": 6 },
  "sparking_yellow_kurti.jpg": { "stock": 18 },
  "white_bridal_saree.jpg": { "stock": 3 }
}
